<div id="footer-links" class="footer-links-container">
    <div class="links-list">
        <div>
            <h3 class="title"><?= $block->escapeHtml(__('Discovery')) ?></h3>
        </div>
        <ul>
            <li><a href="#"><?= $block->escapeHtml(__('New season')) ?></a></li>
            <li><a href="#"><?= $block->escapeHtml(__('Most searched')) ?></a></li>
            <li><a href="#"><?= $block->escapeHtml(__('Most sold')) ?></a></li>

        </ul>
    </div>

    <div class="links-list">
        <div>
            <h3 class="title"><?= $block->escapeHtml(__('About')) ?></h3>
        </div>
        <ul>
            <li><a href="#"><?= $block->escapeHtml(__('Help')) ?></a></li>
            <li><a href="#"><?= $block->escapeHtml(__('Shipping')) ?></a></li>
            <li><a href="#"><?= $block->escapeHtml(__('Affiliate')) ?></a></li>

        </ul>
    </div>

    <div class="links-list">
        <div>
            <h3 class="title"><?= $block->escapeHtml(__('Info')) ?></h3>
        </div>
        <ul>
            <li><a href="#"><?= $block->escapeHtml(__('Contact us')) ?></a></li>
            <li><a href="#"><?= $block->escapeHtml(__('Privacy Policies')) ?></a></li>
            <li><a href="#"><?= $block->escapeHtml(__('Terms & Conditions')) ?></a></li>

        </ul>
    </div>


</div>

