<div class="hero">
    <div class="hero-content">
        <h2 class="hero-leaf"><?= $block->escapeHtml(__('🌱')) ?></h2>
        <h1 class="hero-heading"><?= $block->escapeHtml(__('The nature candle')) ?></h1>
        <p class="hero-description"><?= $block->escapeHtml(__('All handmade with natural soy wax, Candleaf is a companion for all your pleasure moments ')) ?></p>
        <button>Discover our collection</button>
    </div>
</div>
